#!/bin/bash

######################################################
#             Compiles Lang.h frequencies            #
######################################################

set -e    # halt on first error

link=all  # link all binaries by default
linked=no # track whether we linked

case $1 in  
  -nolink) link=none ; shift ;;  # don't link
esac

# use 'g++' as the compiler for debugging.
CPP=g++

# be aggressive about warnings and errors
FLAGS="-g -Wall -Wextra"

# clear out old object files
rm -f language

# compile

$CPP $FLAGS lang.cpp main.cpp analysis.hpp -o language